# Generated by Django 5.2.8 on 2025-11-26 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_vinculacion', models.CharField(choices=[('Planta', 'Planta'), ('Contratista', 'Contratista'), ('Operador', 'Operador')], max_length=50)),
                ('perfil', models.TextField(null=True)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'colaborador',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('vigencia', models.IntegerField()),
                ('codigo', models.CharField(max_length=50, null=True, unique=True)),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('objeto', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'equipo',
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'procedimiento',
            },
        ),
        migrations.CreateModel(
            name='Articulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=255)),
                ('tema', models.TextField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.colaborador')),
            ],
            options={
                'db_table': 'articulacion',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('frecuencia', models.CharField(max_length=50)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.colaborador')),
            ],
            options={
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='ColaboradorContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.colaborador')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.contrato')),
            ],
            options={
                'db_table': 'colaborador_contrato',
            },
        ),
        migrations.AddField(
            model_name='colaborador',
            name='equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.equipo'),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.colaborador')),
            ],
            options={
                'db_table': 'proyecto',
            },
        ),
    ]
